project_name: management-interface

release:
  github:
    owner: TheCacophonyProject
    name: management-interface
  name_template: '{{.Tag}}'

builds:
- id: "managementd"
  binary: "managementd"
  main: "./cmd/managementd"
  goos:
  - linux
  goarch:
  - arm
  goarm:
  - "7"
  ldflags: -s -w -X main.version={{.Version}}
  hooks:
    pre: packr
    post: packr clean
- id: "signal-strength"
  binary: "signal-strength"
  main: "./cmd/signal-strength"
  goos:
  - linux
  goarch:
  - arm
  goarm:
  - "7"
  ldflags: -s -w

nfpms:
- vendor: The Cacophony Project
  homepage: http://cacophony.org.nz/
  maintainer: Cacophony Developers <dev@cacophony.org.nz>
  description: Management interface for Cacophonators
  license: GPL v3.0
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
  formats:
    - deb
  bindir: /usr/bin
  files:
    "_release/cacophonator-management-avahi.service": "/etc/avahi/services/cacophonator-management.service"
    "_release/cacophonator-management-systemd.service": "/etc/systemd/system/cacophonator-management.service"
  config_files:
    "_release/managementd.yaml": "/etc/cacophony/managementd.yaml"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

dist: dist
